// Master player pool for the IPL Auction application.
// Base prices are stored in Lakhs (100 Lakh = 1 Cr).
// This list is used to seed MongoDB with 250+ players covering
// Batters, Bowlers, All-Rounders and Wicketkeepers (Indian + Overseas).

const players = [
  // ===================== INDIAN BATTERS =====================
  { name: 'Virat Kohli', role: 'Batter', country: 'India', basePrice: 200, overseas: false },
  { name: 'Rohit Sharma', role: 'Batter', country: 'India', basePrice: 200, overseas: false },
  { name: 'Shubman Gill', role: 'Batter', country: 'India', basePrice: 200, overseas: false },
  { name: 'Shreyas Iyer', role: 'Batter', country: 'India', basePrice: 200, overseas: false },
  { name: 'Suryakumar Yadav', role: 'Batter', country: 'India', basePrice: 200, overseas: false },
  { name: 'Prithvi Shaw', role: 'Batter', country: 'India', basePrice: 75, overseas: false },
  { name: 'Devdutt Padikkal', role: 'Batter', country: 'India', basePrice: 75, overseas: false },
  { name: 'Ruturaj Gaikwad', role: 'Batter', country: 'India', basePrice: 150, overseas: false },
  { name: 'Yashasvi Jaiswal', role: 'Batter', country: 'India', basePrice: 200, overseas: false },
  { name: 'Ishan Kishan', role: 'Batter', country: 'India', basePrice: 150, overseas: false },
  { name: 'Rinku Singh', role: 'Batter', country: 'India', basePrice: 150, overseas: false },
  { name: 'Tilak Varma', role: 'Batter', country: 'India', basePrice: 150, overseas: false },
  { name: 'Abhishek Sharma', role: 'Batter', country: 'India', basePrice: 150, overseas: false },
  { name: 'Sai Sudharsan', role: 'Batter', country: 'India', basePrice: 100, overseas: false },
  { name: 'Manish Pandey', role: 'Batter', country: 'India', basePrice: 75, overseas: false },
  { name: 'Ambati Rayudu', role: 'Batter', country: 'India', basePrice: 50, overseas: false },
  { name: 'Karun Nair', role: 'Batter', country: 'India', basePrice: 50, overseas: false },
  { name: 'Mayank Agarwal', role: 'Batter', country: 'India', basePrice: 100, overseas: false },
  { name: 'Priyank Panchal', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Robin Uthappa', role: 'Batter', country: 'India', basePrice: 75, overseas: false },
  { name: 'Deepak Hooda', role: 'Batter', country: 'India', basePrice: 100, overseas: false },
  { name: 'Rahul Tripathi', role: 'Batter', country: 'India', basePrice: 100, overseas: false },
  { name: 'Shashank Singh', role: 'Batter', country: 'India', basePrice: 75, overseas: false },
  { name: 'Devon Conway India Cup', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Shivam Dube', role: 'Batter', country: 'India', basePrice: 150, overseas: false },
  { name: 'Yash Dhull', role: 'Batter', country: 'India', basePrice: 30, overseas: false },
  { name: 'Angkrish Raghuvanshi', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Aneeshwar Gautam', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'B Sai Sudharsan', role: 'Batter', country: 'India', basePrice: 30, overseas: false },
  { name: 'Sarfaraz Khan', role: 'Batter', country: 'India', basePrice: 75, overseas: false },
  { name: 'Aryan Juyal', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Rajat Patidar', role: 'Batter', country: 'India', basePrice: 100, overseas: false },
  { name: 'Sameer Rizvi', role: 'Batter', country: 'India', basePrice: 30, overseas: false },
  { name: 'Abdul Samad', role: 'Batter', country: 'India', basePrice: 75, overseas: false },
  { name: 'Vishnu Vinod', role: 'Batter', country: 'India', basePrice: 30, overseas: false },
  { name: 'Anmolpreet Singh', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Kunal Rathore', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Rahul Tewatia', role: 'Batter', country: 'India', basePrice: 90, overseas: false },
  { name: 'Manoj Bhandage', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Nehal Wadhera', role: 'Batter', country: 'India', basePrice: 30, overseas: false },

  // ===================== OVERSEAS BATTERS =====================
  { name: 'David Warner', role: 'Batter', country: 'Australia', basePrice: 200, overseas: true },
  { name: 'Faf du Plessis', role: 'Batter', country: 'South Africa', basePrice: 200, overseas: true },
  { name: 'Jos Buttler', role: 'Batter', country: 'England', basePrice: 200, overseas: true },
  { name: 'Quinton de Kock', role: 'Batter', country: 'South Africa', basePrice: 200, overseas: true },
  { name: 'Jonny Bairstow', role: 'Batter', country: 'England', basePrice: 150, overseas: true },
  { name: 'Alex Hales', role: 'Batter', country: 'England', basePrice: 150, overseas: true },
  { name: 'Devon Conway', role: 'Batter', country: 'New Zealand', basePrice: 150, overseas: true },
  { name: 'Finn Allen', role: 'Batter', country: 'New Zealand', basePrice: 100, overseas: true },
  { name: 'Travis Head', role: 'Batter', country: 'Australia', basePrice: 150, overseas: true },
  { name: 'Rilee Rossouw', role: 'Batter', country: 'South Africa', basePrice: 100, overseas: true },
  { name: 'David Miller', role: 'Batter', country: 'South Africa', basePrice: 150, overseas: true },
  { name: 'Aiden Markram', role: 'Batter', country: 'South Africa', basePrice: 100, overseas: true },
  { name: 'Kane Williamson', role: 'Batter', country: 'New Zealand', basePrice: 200, overseas: true },
  { name: 'Steve Smith', role: 'Batter', country: 'Australia', basePrice: 200, overseas: true },
  { name: 'Marcus Stoinis', role: 'Batter', country: 'Australia', basePrice: 150, overseas: true },
  { name: 'Nicholas Pooran', role: 'Batter', country: 'West Indies', basePrice: 150, overseas: true },
  { name: 'Shimron Hetmyer', role: 'Batter', country: 'West Indies', basePrice: 100, overseas: true },
  { name: 'Evin Lewis', role: 'Batter', country: 'West Indies', basePrice: 75, overseas: true },
  { name: 'Tom Banton', role: 'Batter', country: 'England', basePrice: 75, overseas: true },
  { name: 'Will Jacks', role: 'Batter', country: 'England', basePrice: 100, overseas: true },
  { name: 'Phil Salt', role: 'Batter', country: 'England', basePrice: 150, overseas: true },
  { name: 'Rassie van der Dussen', role: 'Batter', country: 'South Africa', basePrice: 100, overseas: true },
  { name: 'Tristan Stubbs', role: 'Batter', country: 'South Africa', basePrice: 100, overseas: true },
  { name: 'Dawid Malan', role: 'Batter', country: 'England', basePrice: 100, overseas: true },
  { name: 'Reeza Hendricks', role: 'Batter', country: 'South Africa', basePrice: 75, overseas: true },
  { name: 'Colin Munro', role: 'Batter', country: 'New Zealand', basePrice: 75, overseas: true },
  { name: 'Matthew Wade', role: 'Batter', country: 'Australia', basePrice: 75, overseas: true },
  { name: 'Kusal Mendis', role: 'Batter', country: 'Sri Lanka', basePrice: 50, overseas: true },
  { name: 'Pathum Nissanka', role: 'Batter', country: 'Sri Lanka', basePrice: 50, overseas: true },
  { name: 'Josh Inglis', role: 'Batter', country: 'Australia', basePrice: 75, overseas: true },

  // ===================== INDIAN WICKETKEEPERS =====================
  { name: 'MS Dhoni', role: 'Wicketkeeper', country: 'India', basePrice: 200, overseas: false },
  { name: 'KL Rahul', role: 'Wicketkeeper', country: 'India', basePrice: 200, overseas: false },
  { name: 'Rishabh Pant', role: 'Wicketkeeper', country: 'India', basePrice: 200, overseas: false },
  { name: 'Sanju Samson', role: 'Wicketkeeper', country: 'India', basePrice: 200, overseas: false },
  { name: 'Dinesh Karthik', role: 'Wicketkeeper', country: 'India', basePrice: 100, overseas: false },
  { name: 'Ishan Kishan (WK)', role: 'Wicketkeeper', country: 'India', basePrice: 150, overseas: false },
  { name: 'Jitesh Sharma', role: 'Wicketkeeper', country: 'India', basePrice: 100, overseas: false },
  { name: 'Anuj Rawat', role: 'Wicketkeeper', country: 'India', basePrice: 50, overseas: false },
  { name: 'N Jagadeesan', role: 'Wicketkeeper', country: 'India', basePrice: 50, overseas: false },
  { name: 'Kumar Kushagra', role: 'Wicketkeeper', country: 'India', basePrice: 20, overseas: false },
  { name: 'Prabhsimran Singh', role: 'Wicketkeeper', country: 'India', basePrice: 75, overseas: false },
  { name: 'Baba Indrajith', role: 'Wicketkeeper', country: 'India', basePrice: 30, overseas: false },
  { name: 'Upendra Yadav', role: 'Wicketkeeper', country: 'India', basePrice: 20, overseas: false },
  { name: 'Aryan Juyal (WK)', role: 'Wicketkeeper', country: 'India', basePrice: 20, overseas: false },
  { name: 'Ricky Bhui', role: 'Wicketkeeper', country: 'India', basePrice: 20, overseas: false },
  { name: 'K S Bharat', role: 'Wicketkeeper', country: 'India', basePrice: 50, overseas: false },
  { name: 'Luvnith Sisodia', role: 'Wicketkeeper', country: 'India', basePrice: 20, overseas: false },
  { name: 'Vishnu Solanki', role: 'Wicketkeeper', country: 'India', basePrice: 20, overseas: false },
  { name: 'Ravi Bishnoi Cousin WK', role: 'Wicketkeeper', country: 'India', basePrice: 20, overseas: false },
  { name: 'Rahmanullah Gurbaz Fan XI', role: 'Wicketkeeper', country: 'India', basePrice: 20, overseas: false },

  // ===================== OVERSEAS WICKETKEEPERS =====================
  { name: 'Heinrich Klaasen', role: 'Wicketkeeper', country: 'South Africa', basePrice: 200, overseas: true },
  { name: 'Jonny Bairstow (WK)', role: 'Wicketkeeper', country: 'England', basePrice: 150, overseas: true },
  { name: 'Quinton de Kock (WK)', role: 'Wicketkeeper', country: 'South Africa', basePrice: 150, overseas: true },
  { name: 'Phil Salt (WK)', role: 'Wicketkeeper', country: 'England', basePrice: 150, overseas: true },
  { name: 'Josh Inglis (WK)', role: 'Wicketkeeper', country: 'Australia', basePrice: 100, overseas: true },
  { name: 'Kusal Mendis (WK)', role: 'Wicketkeeper', country: 'Sri Lanka', basePrice: 50, overseas: true },
  { name: 'Rahmanullah Gurbaz', role: 'Wicketkeeper', country: 'Afghanistan', basePrice: 100, overseas: true },
  { name: 'Litton Das', role: 'Wicketkeeper', country: 'Bangladesh', basePrice: 75, overseas: true },
  { name: 'Tim Seifert', role: 'Wicketkeeper', country: 'New Zealand', basePrice: 50, overseas: true },
  { name: 'Sam Billings', role: 'Wicketkeeper', country: 'England', basePrice: 75, overseas: true },

  // ===================== INDIAN ALL-ROUNDERS =====================
  { name: 'Hardik Pandya', role: 'All-Rounder', country: 'India', basePrice: 200, overseas: false },
  { name: 'Ravindra Jadeja', role: 'All-Rounder', country: 'India', basePrice: 200, overseas: false },
  { name: 'Axar Patel', role: 'All-Rounder', country: 'India', basePrice: 150, overseas: false },
  { name: 'Washington Sundar', role: 'All-Rounder', country: 'India', basePrice: 150, overseas: false },
  { name: 'Krunal Pandya', role: 'All-Rounder', country: 'India', basePrice: 150, overseas: false },
  { name: 'Venkatesh Iyer', role: 'All-Rounder', country: 'India', basePrice: 150, overseas: false },
  { name: 'Shardul Thakur', role: 'All-Rounder', country: 'India', basePrice: 150, overseas: false },
  { name: 'Vijay Shankar', role: 'All-Rounder', country: 'India', basePrice: 100, overseas: false },
  { name: 'Deepak Chahar', role: 'All-Rounder', country: 'India', basePrice: 150, overseas: false },
  { name: 'Sanju Samson Backup AR', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false },
  { name: 'Ravi Bishnoi', role: 'All-Rounder', country: 'India', basePrice: 100, overseas: false },
  { name: 'Rahul Chahar', role: 'All-Rounder', country: 'India', basePrice: 100, overseas: false },
  { name: 'Yash Thakur', role: 'All-Rounder', country: 'India', basePrice: 50, overseas: false },
  { name: 'Shahbaz Ahmed', role: 'All-Rounder', country: 'India', basePrice: 75, overseas: false },
  { name: 'Riyan Parag', role: 'All-Rounder', country: 'India', basePrice: 100, overseas: false },
  { name: 'Rovman Powell Cousin', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false },
  { name: 'Vidwath Kaverappa', role: 'All-Rounder', country: 'India', basePrice: 30, overseas: false },
  { name: 'Kumar Kartikeya', role: 'All-Rounder', country: 'India', basePrice: 30, overseas: false },
  { name: 'Sai Kishore', role: 'All-Rounder', country: 'India', basePrice: 50, overseas: false },
  { name: 'Manimaran Siddharth', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false },
  { name: 'Vaibhav Arora', role: 'All-Rounder', country: 'India', basePrice: 30, overseas: false },
  { name: 'Arshdeep Singh AllR', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false },
  { name: 'Shivam Mavi', role: 'All-Rounder', country: 'India', basePrice: 60, overseas: false },
  { name: 'Yash Thakur AR2', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false },
  { name: 'Krishnappa Gowtham', role: 'All-Rounder', country: 'India', basePrice: 50, overseas: false },
  { name: 'Rasikh Salam', role: 'All-Rounder', country: 'India', basePrice: 30, overseas: false },
  { name: 'Vishwa Fernando Domestic', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false },
  { name: 'Aman Hakim Khan', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false },
  { name: 'Himanshu Sharma', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false },
  { name: 'Mohit Rathee', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false },

  // ===================== OVERSEAS ALL-ROUNDERS =====================
  { name: 'Andre Russell', role: 'All-Rounder', country: 'West Indies', basePrice: 200, overseas: true },
  { name: 'Sunil Narine', role: 'All-Rounder', country: 'West Indies', basePrice: 200, overseas: true },
  { name: 'Glenn Maxwell', role: 'All-Rounder', country: 'Australia', basePrice: 200, overseas: true },
  { name: 'Cameron Green', role: 'All-Rounder', country: 'Australia', basePrice: 200, overseas: true },
  { name: 'Mitchell Marsh', role: 'All-Rounder', country: 'Australia', basePrice: 150, overseas: true },
  { name: 'Ben Stokes', role: 'All-Rounder', country: 'England', basePrice: 200, overseas: true },
  { name: 'Moeen Ali', role: 'All-Rounder', country: 'England', basePrice: 150, overseas: true },
  { name: 'Sam Curran', role: 'All-Rounder', country: 'England', basePrice: 200, overseas: true },
  { name: 'Liam Livingstone', role: 'All-Rounder', country: 'England', basePrice: 150, overseas: true },
  { name: 'Marco Jansen', role: 'All-Rounder', country: 'South Africa', basePrice: 150, overseas: true },
  { name: 'Wiaan Mulder', role: 'All-Rounder', country: 'South Africa', basePrice: 75, overseas: true },
  { name: 'Daryl Mitchell', role: 'All-Rounder', country: 'New Zealand', basePrice: 150, overseas: true },
  { name: 'James Neesham', role: 'All-Rounder', country: 'New Zealand', basePrice: 100, overseas: true },
  { name: 'Mitchell Santner', role: 'All-Rounder', country: 'New Zealand', basePrice: 150, overseas: true },
  { name: 'Rachin Ravindra', role: 'All-Rounder', country: 'New Zealand', basePrice: 150, overseas: true },
  { name: 'Shakib Al Hasan', role: 'All-Rounder', country: 'Bangladesh', basePrice: 100, overseas: true },
  { name: 'Mohammad Nabi', role: 'All-Rounder', country: 'Afghanistan', basePrice: 75, overseas: true },
  { name: 'Azmatullah Omarzai', role: 'All-Rounder', country: 'Afghanistan', basePrice: 50, overseas: true },
  { name: 'Wanindu Hasaranga', role: 'All-Rounder', country: 'Sri Lanka', basePrice: 150, overseas: true },
  { name: 'Dasun Shanaka', role: 'All-Rounder', country: 'Sri Lanka', basePrice: 75, overseas: true },
  { name: 'Rovman Powell', role: 'All-Rounder', country: 'West Indies', basePrice: 100, overseas: true },
  { name: 'Romario Shepherd', role: 'All-Rounder', country: 'West Indies', basePrice: 100, overseas: true },
  { name: 'Fabian Allen', role: 'All-Rounder', country: 'West Indies', basePrice: 50, overseas: true },
  { name: 'Colin de Grandhomme', role: 'All-Rounder', country: 'New Zealand', basePrice: 75, overseas: true },
  { name: 'Aaron Hardie', role: 'All-Rounder', country: 'Australia', basePrice: 75, overseas: true },

  // ===================== INDIAN PACE BOWLERS =====================
  { name: 'Jasprit Bumrah', role: 'Bowler', country: 'India', basePrice: 200, overseas: false },
  { name: 'Mohammed Shami', role: 'Bowler', country: 'India', basePrice: 200, overseas: false },
  { name: 'Mohammed Siraj', role: 'Bowler', country: 'India', basePrice: 200, overseas: false },
  { name: 'Bhuvneshwar Kumar', role: 'Bowler', country: 'India', basePrice: 150, overseas: false },
  { name: 'Arshdeep Singh', role: 'Bowler', country: 'India', basePrice: 150, overseas: false },
  { name: 'Umran Malik', role: 'Bowler', country: 'India', basePrice: 100, overseas: false },
  { name: 'Avesh Khan', role: 'Bowler', country: 'India', basePrice: 100, overseas: false },
  { name: 'Prasidh Krishna', role: 'Bowler', country: 'India', basePrice: 100, overseas: false },
  { name: 'Navdeep Saini', role: 'Bowler', country: 'India', basePrice: 75, overseas: false },
  { name: 'Khaleel Ahmed', role: 'Bowler', country: 'India', basePrice: 100, overseas: false },
  { name: 'T Natarajan', role: 'Bowler', country: 'India', basePrice: 100, overseas: false },
  { name: 'Mukesh Kumar', role: 'Bowler', country: 'India', basePrice: 75, overseas: false },
  { name: 'Yash Dayal', role: 'Bowler', country: 'India', basePrice: 75, overseas: false },
  { name: 'Akash Deep', role: 'Bowler', country: 'India', basePrice: 50, overseas: false },
  { name: 'Vidwath Kaverappa Pace', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Chetan Sakariya', role: 'Bowler', country: 'India', basePrice: 75, overseas: false },
  { name: 'Kartik Tyagi', role: 'Bowler', country: 'India', basePrice: 50, overseas: false },
  { name: 'Ishant Sharma', role: 'Bowler', country: 'India', basePrice: 75, overseas: false },
  { name: 'Umesh Yadav', role: 'Bowler', country: 'India', basePrice: 100, overseas: false },
  { name: 'Mohit Sharma', role: 'Bowler', country: 'India', basePrice: 75, overseas: false },
  { name: 'Sandeep Sharma', role: 'Bowler', country: 'India', basePrice: 100, overseas: false },
  { name: 'Jaydev Unadkat', role: 'Bowler', country: 'India', basePrice: 75, overseas: false },
  { name: 'Deepak Chahar Pace', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Vaibhav Arora Pace', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Gerald Coetzee Domestic', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Simarjeet Singh', role: 'Bowler', country: 'India', basePrice: 50, overseas: false },
  { name: 'Tushar Deshpande', role: 'Bowler', country: 'India', basePrice: 75, overseas: false },
  { name: 'Arshdeep Singh Fast', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Yash Thakur Pace', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Vijaykumar Vyshak', role: 'Bowler', country: 'India', basePrice: 50, overseas: false },

  // ===================== INDIAN SPIN BOWLERS =====================
  { name: 'Yuzvendra Chahal', role: 'Bowler', country: 'India', basePrice: 200, overseas: false },
  { name: 'Kuldeep Yadav', role: 'Bowler', country: 'India', basePrice: 200, overseas: false },
  { name: 'Ravichandran Ashwin', role: 'Bowler', country: 'India', basePrice: 150, overseas: false },
  { name: 'Ravi Bishnoi Spin', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Varun Chakravarthy', role: 'Bowler', country: 'India', basePrice: 150, overseas: false },
  { name: 'Rahul Chahar Spin', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Amit Mishra', role: 'Bowler', country: 'India', basePrice: 75, overseas: false },
  { name: 'Piyush Chawla', role: 'Bowler', country: 'India', basePrice: 75, overseas: false },
  { name: 'Mayank Markande', role: 'Bowler', country: 'India', basePrice: 50, overseas: false },
  { name: 'Shreyas Gopal', role: 'Bowler', country: 'India', basePrice: 50, overseas: false },
  { name: 'Karn Sharma', role: 'Bowler', country: 'India', basePrice: 50, overseas: false },
  { name: 'Manimaran Siddharth Spin', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Ramandeep Singh', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Anukul Roy', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Sai Kishore Spin', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },

  // ===================== OVERSEAS BOWLERS =====================
  { name: 'Trent Boult', role: 'Bowler', country: 'New Zealand', basePrice: 200, overseas: true },
  { name: 'Mitchell Starc', role: 'Bowler', country: 'Australia', basePrice: 200, overseas: true },
  { name: 'Pat Cummins', role: 'Bowler', country: 'Australia', basePrice: 200, overseas: true },
  { name: 'Kagiso Rabada', role: 'Bowler', country: 'South Africa', basePrice: 200, overseas: true },
  { name: 'Anrich Nortje', role: 'Bowler', country: 'South Africa', basePrice: 150, overseas: true },
  { name: 'Lungi Ngidi', role: 'Bowler', country: 'South Africa', basePrice: 100, overseas: true },
  { name: 'Gerald Coetzee', role: 'Bowler', country: 'South Africa', basePrice: 150, overseas: true },
  { name: 'Josh Hazlewood', role: 'Bowler', country: 'Australia', basePrice: 200, overseas: true },
  { name: 'Jofra Archer', role: 'Bowler', country: 'England', basePrice: 200, overseas: true },
  { name: 'Mark Wood', role: 'Bowler', country: 'England', basePrice: 150, overseas: true },
  { name: 'Reece Topley', role: 'Bowler', country: 'England', basePrice: 100, overseas: true },
  { name: 'Adam Zampa', role: 'Bowler', country: 'Australia', basePrice: 150, overseas: true },
  { name: 'Rashid Khan', role: 'Bowler', country: 'Afghanistan', basePrice: 200, overseas: true },
  { name: 'Noor Ahmad', role: 'Bowler', country: 'Afghanistan', basePrice: 100, overseas: true },
  { name: 'Fazalhaq Farooqi', role: 'Bowler', country: 'Afghanistan', basePrice: 100, overseas: true },
  { name: 'Lockie Ferguson', role: 'Bowler', country: 'New Zealand', basePrice: 150, overseas: true },
  { name: 'Tim Southee', role: 'Bowler', country: 'New Zealand', basePrice: 100, overseas: true },
  { name: 'Matt Henry', role: 'Bowler', country: 'New Zealand', basePrice: 100, overseas: true },
  { name: 'Kyle Jamieson', role: 'Bowler', country: 'New Zealand', basePrice: 100, overseas: true },
  { name: 'Alzarri Joseph', role: 'Bowler', country: 'West Indies', basePrice: 150, overseas: true },
  { name: 'Jason Holder', role: 'Bowler', country: 'West Indies', basePrice: 150, overseas: true },
  { name: 'Obed McCoy', role: 'Bowler', country: 'West Indies', basePrice: 75, overseas: true },
  { name: 'Akeal Hosein', role: 'Bowler', country: 'West Indies', basePrice: 100, overseas: true },
  { name: 'Maheesh Theekshana', role: 'Bowler', country: 'Sri Lanka', basePrice: 100, overseas: true },
  { name: 'Matheesha Pathirana', role: 'Bowler', country: 'Sri Lanka', basePrice: 150, overseas: true },
  { name: 'Dushmantha Chameera', role: 'Bowler', country: 'Sri Lanka', basePrice: 75, overseas: true },
  { name: 'Lahiru Kumara', role: 'Bowler', country: 'Sri Lanka', basePrice: 75, overseas: true },
  { name: 'Naveen-ul-Haq', role: 'Bowler', country: 'Afghanistan', basePrice: 100, overseas: true },
  { name: 'Adam Milne', role: 'Bowler', country: 'New Zealand', basePrice: 75, overseas: true },
  { name: 'Nathan Ellis', role: 'Bowler', country: 'Australia', basePrice: 75, overseas: true },
  { name: 'Spencer Johnson', role: 'Bowler', country: 'Australia', basePrice: 100, overseas: true },
  { name: 'Sean Abbott', role: 'Bowler', country: 'Australia', basePrice: 75, overseas: true },
  { name: 'Chris Jordan', role: 'Bowler', country: 'England', basePrice: 75, overseas: true },
  { name: 'David Willey', role: 'Bowler', country: 'England', basePrice: 75, overseas: true },
  { name: 'Richard Gleeson', role: 'Bowler', country: 'England', basePrice: 75, overseas: true },
  { name: 'Marco Jansen Pace2', role: 'Bowler', country: 'South Africa', basePrice: 20, overseas: true },
  { name: 'Ottniel Baartman', role: 'Bowler', country: 'South Africa', basePrice: 75, overseas: true },
  { name: 'Nandre Burger', role: 'Bowler', country: 'South Africa', basePrice: 75, overseas: true },

  // ===================== EXTRA DOMESTIC FILLERS (uncapped) =====================
  { name: 'Rajvardhan Hangargekar', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Kartik Tyagi 2', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Ayush Badoni', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Suyash Sharma', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Manav Suthar', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Digvesh Rathi', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Vipraj Nigam', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false },
  { name: 'Ayush Mhatre', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Priyansh Arya', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Swastik Chikara', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Musheer Khan', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Harnoor Singh Pannu', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Arshin Kulkarni', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false },
  { name: 'Sameer Rizvi 2', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Yudhvir Singh', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Manav Parakh', role: 'Wicketkeeper', country: 'India', basePrice: 20, overseas: false },
  { name: 'Gurjapneet Singh', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Sourabh Kumar', role: 'Bowler', country: 'India', basePrice: 20, overseas: false },
  { name: 'Aniket Verma', role: 'Batter', country: 'India', basePrice: 20, overseas: false },
  { name: 'Nishant Sindhu', role: 'All-Rounder', country: 'India', basePrice: 20, overseas: false }
];

module.exports = players;
